language: java
sudo: true
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"-- refresh-dependencies"* ]]; ./gradlew downloadDependencies ; fi ;
script:
  - ./gradlew build
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)