language: java
sudo: true
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
  - pip install Sphinx
 #- if [[ $TRAVIS_COMMIT_MESSAGE == *"--refresh-dependencies"* ]]; then ./gradlew downloadDependencies --debug ; fi ;
script:
  - pip install https://github.com/Shynixn/sphinx_rtd_theme/archive/C1.0.zip
  - ./gradlew generateWikiPages
  - ./gradlew build
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)