language: java
sudo: true
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
  - sudo apt-get install python3-pip
script:
  - ./gradlew build
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)