language: java
sudo: true
jdk:
  - oraclejdk8
install:
  - gradle wrapper --gradle-version 4.2
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build
after_success:
  - bash <(curl -s https://codecov.io/bash)